"""
This file contains all the names used in ProbLog.\n
Define them here and use the respective constants for consistency.
"""

CELL = 'cell'
GOOD = 'good'
NEUTRAL = 'neutral'
BAD = 'bad'
TURN = 'turn'
BOARD = 'board'
PLAY = 'play'
WIN = 'win'
WIN1 = 'win1'
WIN2 = 'win2'
WIN3 = 'win3'
WIN4 = 'win4'
WIN5 = 'win5'
WIN6 = 'win6'
WIN7 = 'win7'
WIN8 = 'win8'
LOSE = 'lose'
LOSE1 = 'lose1'
LOSE2 = 'lose2'
LOSE3 = 'lose3'
LOSE4 = 'lose4'
LOSE5 = 'lose5'
LOSE6 = 'lose6'
LOSE7 = 'lose7'
LOSE8 = 'lose8'
A = 'A'
B = 'B'
ANY = '_'
X = 'x'
O = 'o'
N = 'n'
E = 'e'
T = 't'