# term names, centralized
SQUARE_GOOD = 'square_good'
SQUARE_NEUTRAL = 'square_neutral'
SQUARE_BAD = 'square_bad'
TURN = 'turn'
BOARD = 'board'
CHOOSE = 'choose'
WIN = 'win'
LOSE = 'lose'
A = 'A'
B = 'B'
ANY = '_'